export const LOGIN_REQUEST_DATA = "LOGIN_REQUEST_DATA";
export const LOGIN_SUCCESS_DATA = "LOGIN_SUCCESS_DATA";
export const LOGIN_FAILURE_DATA = "LOGIN_FAILURE_DATA";

export const REGISTER_REQUEST_DATA = "REGISTER_REQUEST_DATA";
export const REGISTER_SUCCESS_DATA = "REGISTER_SUCCESS_DATA";
export const REGISTER_FAILURE_DATA = "REGISTER_FAILURE_DATA";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
